org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=goldenpotions
mod.name=Golden Potions
mod.group=me.pajic
mod.version=1.0.3
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=Brew potions from golden food items instead of eating them
mod.sources_url=https://github.com/pajicadvance/golden-potions
mod.homepage_url=https://modrinth.com/mod/golden-potions
mod.issues_url=https://github.com/pajicadvance/golden-potions/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.parchment=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.mixson=v1.4.0
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]

publish.modrinth=gRalVCmr
publish.curseforge=1337903
publish.github=false
